// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearProcessedFiles() {
  return window['go']['main']['App']['ClearProcessedFiles']();
}

export function CreateTorrent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTorrent'](arg1, arg2, arg3, arg4);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function GetMediaInfo(arg1) {
  return window['go']['main']['App']['GetMediaInfo'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function LaCaleLogin(arg1, arg2) {
  return window['go']['main']['App']['LaCaleLogin'](arg1, arg2);
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function MarkProcessed(arg1) {
  return window['go']['main']['App']['MarkProcessed'](arg1);
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function RemoveFromQBittorrent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RemoveFromQBittorrent'](arg1, arg2, arg3, arg4);
}

export function SaveNfo(arg1, arg2) {
  return window['go']['main']['App']['SaveNfo'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function UploadToLaCale(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['UploadToLaCale'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function UploadToQBittorrent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadToQBittorrent'](arg1, arg2, arg3, arg4);
}
