// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {http} from '../models';

export function ClearProcessedFiles():Promise<void>;

export function CreateTorrent(arg1:string,arg2:Array<string>,arg3:string,arg4:boolean):Promise<string>;

export function DeleteFile(arg1:string):Promise<void>;

export function GetDirectorySize(arg1:string):Promise<string>;

export function GetMediaInfo(arg1:string):Promise<string>;

export function GetSettings():Promise<main.AppSettings>;

export function LaCaleLogin(arg1:string,arg2:string):Promise<http.Client>;

export function ListDirectory(arg1:string):Promise<Array<main.FileInfo>>;

export function MarkProcessed(arg1:string):Promise<void>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function RemoveFromQBittorrent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveNfo(arg1:string,arg2:string):Promise<string>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SelectDirectory():Promise<string>;

export function UploadToLaCale(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:main.ReleaseInfo,arg8:string,arg9:string,arg10:string):Promise<void>;

export function UploadToQBittorrent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
